### ISSUE TITLE
golang is included in the launch layer

### ISSUE THREAD

**Issue by bstick12** [cloudfoundry/go-cnb#2]
The build plan defines the golang dependency as to **not** be included in the launch layer
https://github.com/cloudfoundry/go-cnb/blob/7c44e967af40fc4337ceadb230d1168f55bf02d6/cmd/detect/main.go#L50-L53

The contribute code sets the `launch` value to true based on the presence of the `launch` metadata rather than the value of the metadata.

https://github.com/cloudfoundry/go-cnb/blob/7c44e967af40fc4337ceadb230d1168f55bf02d6/golang/golang.go#L42-L48

**Comment by chhhavi** [comment]
This has been addressed in this PR (https://github.com/cloudfoundry/go-cnb/pull/3), which is now merged. Closing.
