### ISSUE TITLE
Go CNB requires a `buildpack.yml` structure that isn't compatible with other buildpacks

### ISSUE THREAD

**Issue by bstick12** [cloudfoundry/go-cnb#4]
What version of the buildpack you are using?
0.0.3

If you were attempting to accomplish a task, what was it you were attempting to do?
Building a golang application with `go-cnb` and `dep-cnb`

What did you expect to happen?
That I could build the application

What was the actual behavior?

When using the pack CLI with local version of the builder and a simple go applicatation that uses dep. 

```
pack build helloworld --builder cloudfoundry/cnb:cflinuxfs3 --buildpack ~/workspace/go-cnb/compiled/ --buildpack /Users/pivotal/workspace/dep-cnb/compiled --path ~/go/src/go-hello-world
```

The detection fails with the following. 

```
===> DETECTING
[detector] Trying group 1 out of 1 with 2 buildpacks...
[detector] ======== Output: Go Buildpack ========
[detector] yaml: unmarshal errors:
[detector]   line 2: cannot unmarshal !!str `github....` into struct { Version string "yaml:\"version\"" }
[detector] ======== Output: Dep Buildpack ========
[detector] Found buildpack.yml
[detector] ======== Results ========
[detector] fail: Go Buildpack
[detector] pass: Dep Buildpack
[detector] Error: failed to detect
```

The buildpack.yml is 

```
---
import-path: github.com/pivotal/go-hello-world
```

`import-path` is required by the `dep-cnb`

The problem seems to be with using the helper function from 

https://github.com/cloudfoundry/go-cnb/blob/master//vendor/github.com/cloudfoundry/libcfbuildpack/helper/read_buildpack_yaml.go#L30:6

which enforces a structure across all buildpacks

Can you provide a sample app?
Any go-dep app will suffice

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by bstick12** [comment]
@cmccarthy101

**Comment by Zanadar** [comment]
@bstick12 We've got a document around this: https://docs.google.com/document/d/1l-PJ0KTY1hplHxiWcjZVIS1kOO76vY5O7KGVo29vfE4/edit?usp=sharing . Basically the stucture of buildpack.yml should be:
```
go:
  import-path: whatever/path/you/like.com
```

**Comment by bstick12** [comment]
@Zanadar The dep-cnb requires the import path at the root of the `buildpack.yml` - https://github.com/cloudfoundry/dep-cnb/blob/236f0e22958bc668707e2a2a72ce6639a4517a60/cmd/detect/main.go#L67-L79

**Comment by Zanadar** [comment]
The dep-cnb should have `import-path` nested under the go key. We've standardized on a structure for buildpack.yml and will be changing that.
